package Brainbase::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Brainbase::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:brainbase',
        user => 'Username_here',
        password => 'your_password_here',
        AutoCommit => q{1},
    }
);

=head1 NAME

Brainbase::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Brainbase>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Brainbase::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Alex Paciorkowski

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
